---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/pjkgvs3n0bxh/nf.anhnt.id.vn    # Đường dẫn nơi tệp sẽ được triển khai đến
    - /bin/cp -R * $DEPLOY_PATH                     # Sao chép tất cả các tệp sang đường dẫn triển khai
    - /bin/chmod -R 755 $DEPLOY_PATH                   # Cấp quyền thực thi cho các tệp triển khai
    - /bin/chown -R pjkgvs3n0bxh:pjkgvs3n0bxh $DEPLOY_PATH      # Gán quyền sở hữu cho người dùng và nhóm người dùng
    - /bin/rm -rf $DEPLOY_PATH/.cpanel.yml               # Xóa tệp cấu hình triển khai
    - cd $DEPLOY_PATH                           # Đổi thư mục làm việc hiện tại thành thư mục triển khai
    - /usr/local/bin/composer install --no-dev --optimize-autoloader  # Cài đặt các gói phụ thuộc
    - /usr/local/bin/npm run build --production            # Xây dựng tệp tĩnh
